Demo
knative/test-infra pull request #2438
Opened 2020-09-17 17:05 UTC by Yizong98

add deployments to demo

2020-09-17 17:05 UTC, mattmoor reviewed
<!--typo-bot-->

2020-09-17 17:05 UTC, mattmoor commented on tools/dkcm/mainservice/mainservice.go
> +// Reponse to Prow
<!--typo-bot-->
Found potential misspelling(s):
```suggestion
// Response to Prow
```

2020-09-17 17:08 UTC, mattmoor reviewed
<!--typo-bot-->

2020-09-17 17:08 UTC, mattmoor commented on tools/dkcm/mainservice/mainservice.go
> +// Reponse to Prow
<!--typo-bot-->
Found potential misspelling(s):
```suggestion
// Response to Prow
```

2020-09-17 17:08 UTC, chaodaiG commented on common.mk
>  # Do not allow server update from wrong branch or dirty working space
revert this file

2020-09-17 17:08 UTC, chaodaiG commented on images/simple-image.mk
> +PROJECT    ?= cris-intern-demo-project
revert this file

2020-09-17 17:08 UTC, chaodaiG commented on images/tool/Dockerfile
> +RUN GO111MODULE=on go get -u sigs.k8s.io/kubetest2
Revert this file

2020-09-17 17:08 UTC, chaodaiG commented on tools/dkcm/gke_deployment/Makefile
> +# Copyright 2020 The Knative Authors
Let's delete this file for now

2020-09-17 17:12 UTC, chaodaiG commented on vendor/sigs.k8s.io/yaml/OWNERS
> +# See the OWNERS docs at https://go.k8s.io/owners
delete this

2020-09-17 17:12 UTC, chaodaiG commented on tools/dkcm/gke_deployment/dkcm_deployment.yaml
> +# Copyright 2019 The Knative Authors
Let's delete this file for now as well

2020-09-17 17:20 UTC, mattmoor reviewed
<!--typo-bot-->

2020-09-17 17:20 UTC, mattmoor commented on tools/dkcm/mainservice/mainservice.go
> +// Reponse to Prow
<!--typo-bot-->
Found potential misspelling(s):
```suggestion
// Response to Prow
```

2020-09-17 17:23 UTC, mattmoor reviewed
<!--typo-bot-->

2020-09-17 17:23 UTC, mattmoor commented on tools/dkcm/mainservice/mainservice.go
> +// Reponse to Prow
<!--typo-bot-->
Found potential misspelling(s):
```suggestion
// Response to Prow
```

2020-09-17 17:33 UTC, mattmoor reviewed
<!--typo-bot-->

2020-09-17 17:33 UTC, mattmoor commented on tools/dkcm/mainservice/mainservice.go
> +// Reponse to Prow
<!--typo-bot-->
Found potential misspelling(s):
```suggestion
// Response to Prow
```

2020-09-17 18:45 UTC, coryrc commented
/uncc coryrc

2020-09-17 19:01 UTC, chaodaiG requested changes

2020-09-17 19:01 UTC, chaodaiG commented on tools/dkcm/mainservice/mainservice.go
> +		log.Printf("Failed to acquire a project from boskos: %v", err)
I feel the caller want to know that this failed

2020-09-17 19:45 UTC, Yizong98 commented on tools/dkcm/clerk/sql_params.go
> +func UpdateStringField(key string, value string) UpdateOption {
cool.

2020-09-17 20:17 UTC, Yizong98 commented on tools/dkcm/mainservice/mainservice.go
> +		return fmt.Errorf("failed to create Boskos client: %v", err)
kk

2020-09-17 20:37 UTC, Yizong98 commented on tools/dkcm/mainservice/mainservice.go
> +	serviceAccount = gcpServiceAccount
for creating clusters

2020-09-17 21:42 UTC, Yizong98 commented on tools/dkcm/mainservice/mainservice.go
> +		dbClient.UpdateRequest(r.ID, clerk.UpdateNumField("ClusterID", clusterID))
solved

2020-09-18 07:46 UTC, Yizong98 commented
/retest

2020-09-18 21:20 UTC, mattmoor reviewed
<!--gotool-bot-->
Produced via:
  `gofmt -s -w $(find -path './vendor' -prune -o -path './third_party' -prune -o -name '*.pb.go' -prune -o -type f -name '*.go' -print)`
  `goimports -w $(find -name '*.go' | grep -v vendor | grep -v third_party | grep -v .pb.go | grep -v wire_gen.go)`

2020-09-18 21:20 UTC, mattmoor commented on tools/dkcm/mainservice/mainservice.go
> +	mux 				 sync.Mutex
<!--gotool-bot-->
Format Go code:
```suggestion
	mux                  sync.Mutex
```

2020-09-18 21:48 UTC, chizhg commented on tools/dkcm/mainservice/mainservice.go
> +		go CreateCluster(cp)
Delete this line, since `checkPoolCap` is already run as a goroutine.

2020-09-23 21:07 UTC, chaodaiG commented on tools/dkcm/mainservice/mainservice.go
> +	}
We should switch the order here, delete from db before releasing

2020-09-23 21:07 UTC, chaodaiG commented on tools/dkcm/mainservice/mainservice.go
> +	defer wg.Done()
this happens after cluster is created, which will result in chanLock held for several minutes

2020-09-23 21:57 UTC, mattmoor reviewed
<!--gotool-bot-->
Produced via:
  `gofmt -s -w $(find -path './vendor' -prune -o -path './third_party' -prune -o -name '*.pb.go' -prune -o -type f -name '*.go' -print)`
  `goimports -w $(find -name '*.go' | grep -v vendor | grep -v third_party | grep -v .pb.go | grep -v wire_gen.go)`

2020-09-23 21:57 UTC, mattmoor commented on tools/dkcm/mainservice/constants.go
> +	Fail                 = "Failed"
<!--gotool-bot-->
Format Go code:
```suggestion
	// four statuses of cluster
	Ready = "Ready"
	WIP   = "WIP"
	InUse = "In Use"
	Fail  = "Failed"
```

2020-09-23 21:57 UTC, mattmoor commented on tools/dkcm/mainservice/constants.go
> +	ClusterID            = "ClusterID"
<!--gotool-bot-->
Format Go code:
```suggestion
	Status    = "Status"
	ClusterID = "ClusterID"
```

2020-09-23 21:57 UTC, mattmoor commented on tools/dkcm/mainservice/constants.go
> +	CheckInterval        = 2
<!--gotool-bot-->
Format Go code:
```suggestion
	CheckInterval = 2
```

2020-09-23 22:33 UTC, chizhg commented on tools/dkcm/mainservice/mainservice.go
> +	wg.Done()
This should be changed to `defer wg.Done()` and moved to the top of this function.

2020-09-23 23:31 UTC, chizhg commented
/lgtm
Defer to Chao for approval.

2020-09-23 23:42 UTC, chizhg commented
/approve

2020-09-23 23:51 UTC, merged